//Enumerador para permisos
export enum Functions {
  USER_REVIEW = 1,
  USER_CREATE = 2,
  USER_UPDATE = 3,
  USER_DELETE = 4,

  PROFILE_REVIEW = 5,
  PROFILE_CREATE = 6,
  PROFILE_UPDATE = 7,
  PROFILE_DELETE = 8,

  LOG_REVIEW = 9,

  APP_REVIEW = 10,

  NEWS_REVIEW = 11,
  NEWS_CREATE = 12,
  NEWS_UPDATE = 13,
  NEWS_DELETE = 14,

  VACCINE_REVIEW = 15,
  VACCINE_CREATE = 16,
  VACCINE_UPDATE = 17,
  VACCINE_DELETE = 18,

  DISEASE_REVIEW = 19,
  DISEASE_CREATE = 20,
  DISEASE_UPDATE = 21,
  DISEASE_DELETE = 22,

  EFFECTS_REVIEW = 23,
  EFFECTS_CREATE = 24,
  EFFECTS_UPDATE = 25,
  EFFECTS_DELETE = 26,

  COUNTRY_REVIEW = 27,
  COUNTRY_CREATE = 28,
  COUNTRY_UPDATE = 29,
  COUNTRY_DELETE = 30,

  SCHEME_REVIEW = 31,
  SCHEME_CREATE = 32,
  SCHEME_UPDATE = 33,
  SCHEME_DELETE = 34,

  TRAVEL_REVIEW = 35,
  TRAVEL_CREATE = 36,
  TRAVEL_UPDATE = 37,
  TRAVEL_DELETE = 38,

  VCOUNTRY_REVIEW = 39,
  VCOUNTRY_CREATE = 40,
  VCOUNTRY_UPDATE = 41,
  VCOUNTRY_DELETE = 42,

  
  ADMIN1_REVIEW = 47,
  ADMIN1_CREATE = 48,
  ADMIN1_UPDATE = 49,
  ADMIN1_DELETE = 50,
  
  ADMIN2_REVIEW = 51,
  ADMIN2_CREATE = 52,
  ADMIN2_UPDATE = 53,
  ADMIN2_DELETE = 54,

  HCENTER_REVIEW = 43,
  HCENTER_CREATE = 44,
  HCENTER_UPDATE = 45,
  HCENTER_DELETE = 46,
  
  VCENTER_REVIEW = 55,
  VCENTER_CREATE = 56,
  VCENTER_UPDATE = 57,
  VCENTER_DELETE = 58,

  VPOINT_REVIEW = 59,
  VPOINT_CREATE = 60,
  VPOINT_UPDATE = 61,
  VPOINT_DELETE = 62,

  UPLOAD = 63,
  LIBRARY_REVIEW = 64

}
